[tool.poetry]
name = "configparser"
version = "0.1.0"
description = "Download plugin README and extract config options"
authors = []

[tool.poetry.scripts]
poetry = "poetry.console.application:main"

[tool.poetry.dependencies]
python = "^3.10"
tree-sitter = "*"
coloredlogs = "*"
SLPP = "*"
setuptools = "*"

[build-system]
requires = ["poetry-core~=1.0"]
build-backend = "poetry.core.masonry.api"
