[book]
title = "NixNeovim Documentation"
authors = ["Joscha Loos"]
description = "Official documentation for NixNeoim."
language = "en"
multilingual = false
src = "."

[output.html.fold]
enable = true
level = 0
