name: Run all nix checks

runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v26
    - name: Check Libs
      shell: bash
      run: |
        nix build .#checks.x86_64-linux.lib -L

    - name: Basic checks
      shell: bash
      run: |
        nix build .#checks.x86_64-linux.basic-group1 -L
        nix build .#checks.x86_64-linux.basic-group2 -L
        nix build .#checks.x86_64-linux.basic-group3 -L

    - name: Check plugins
      shell: bash
      run: |
        nix build .#checks.x86_64-linux.plugins -L

    - name: Check colorschemes
      shell: bash
      run: |
        nix build .#checks.x86_64-linux.basic-colorschemes -L
        nix build .#checks.x86_64-linux.colorschemes -L

    - name: Check neovim module
      shell: bash
      run: |
        nix build .#checks.x86_64-linux.neovim -L
