# name: Update inputs

# on:
  # schedule:
    # - cron: "5 14 * * 0,4"
  # workflow_dispatch:

# jobs:
  # update-plugins:
    # runs-on: ubuntu-latest
    # name: Update plugins
    # steps:
      # - uses: actions/checkout@v3
        # with:
          # token: ${{ github.token }}
          # ref: ${{ github.head_ref }}
      # - uses: cachix/install-nix-action@v20
        # with:
          # github_access_token: ${{ github.token }}
      # - name: Update inputs
        # run: |
          # nix flake update
      # - name: Commit changes
        # uses: stefanzweifel/git-auto-commit-action@v4
        # with:
          # commit_user_name: NixNeovim-CI
          # commit_user_email: ""
          # commit_author: ""
          # commit_message: 'CI: update inputs '
          # file_pattern: flake.lock
          # push_options: '--force'

name: Update inputs, Create PR, and Run Tests

on:
  schedule:
    - cron: "5 14 * * 0,4"
  workflow_dispatch:

jobs:
  update-inputs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ github.token }}
          ref: ${{ github.head_ref }}
      - uses: cachix/install-nix-action@v20
        with:
          github_access_token: ${{ github.token }}
      - name: Update inputs
        run: |
          nix flake update

      # - name: Commit changes
        # uses: stefanzweifel/git-auto-commit-action@v4
        # with:
          # commit_user_name: NixNeovim-CI
          # commit_user_email: ""
          # commit_author: ""
          # commit_message: 'CI: update inputs '
          # file_pattern: flake.lock
          # # push_options: '--force'
          # branch: update-inputs-bot
          # create_branch: true

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ github.token }}
          title: "[BOT] Update inputs"
          branch: update-inputs-bot # merge from this branch
          base: main # merge into this branch
          delete-branch: false
          add-paths: flake.lock

  nix-flake-check:
    runs-on: ubuntu-latest
    needs: update-inputs
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ github.token }}
          ref: update-inputs-bot
      - uses: cachix/install-nix-action@v20
        with:
          github_access_token: ${{ github.token }}

      - name: Check Libs
        run: |
          nix build .#checks.x86_64-linux.lib -L

      - name: Basic checks
        run: |
          nix build .#checks.x86_64-linux.basic-group1 -L
          nix build .#checks.x86_64-linux.basic-group2 -L
          nix build .#checks.x86_64-linux.basic-group3 -L

      - name: Check plugins
        run: |
          nix build .#checks.x86_64-linux.plugins -L

      - name: Check colorschemes
        run: |
          nix build .#checks.x86_64-linux.basic-colorschemes -L
          nix build .#checks.x86_64-linux.colorschemes -L

      - name: Check neovim module
        run: |
          nix build .#checks.x86_64-linux.neovim -L

  merge:
    runs-on: ubuntu-latest
    needs: nix-flake-check
    steps:
      - name: Merge Pull Request
        if: success()
        uses: actions/github-script@v5
        with:
          github-token: ${{ github.token }}
          script: |
            await github.pulls.merge({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
            });
