name: Update inputs with PR

on:
  schedule:
    - cron: "5 14 * * 0,4"
  workflow_dispatch:

jobs:
  update-inputs:
    runs-on: ubuntu-latest
    name: Update Inputs
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ github.token }}
          ref: ${{ github.head_ref }}
      - uses: cachix/install-nix-action@v26
        with:
          github_access_token: ${{ github.token }}

      - name: Update inputs
        run: |
          nix flake update

      - name: Run checks
        uses: NixNeovim/NixNeovim/.github/actions/checks@main

      - name: Commit changes
        if: success()
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_user_name: NixNeovim-CI
          commit_user_email: ""
          commit_author: ""
          commit_message: 'CI: update inputs'
          file_pattern: flake.lock
          push_options: '--force'

      - name: Create Pull Request
        if: failure()
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ github.token }}
          title: "[BOT] Update inputs failed"
          branch: update-inputs-bot # merge from this branch
          base: main # merge into this branch
          delete-branch: true
          add-paths: flake.lock
          labels: automerge
          body: "Updating inputs failed. See ${{ github.workflow }}"
