# name: Update inputs

# on:
  # schedule:
    # - cron: "5 14 * * 0,4"
  # workflow_dispatch:

# jobs:
  # update-plugins:
    # runs-on: ubuntu-latest
    # name: Update plugins
    # steps:
      # - uses: actions/checkout@v3
        # with:
          # token: ${{ github.token }}
          # ref: ${{ github.head_ref }}
      # - uses: cachix/install-nix-action@v20
        # with:
          # github_access_token: ${{ github.token }}
      # - name: Update inputs
        # run: |
          # nix flake update
      # - name: Commit changes
        # uses: stefanzweifel/git-auto-commit-action@v4
        # with:
          # commit_user_name: NixNeovim-CI
          # commit_user_email: ""
          # commit_author: ""
          # commit_message: 'CI: update inputs '
          # file_pattern: flake.lock
          # push_options: '--force'

name: Update inputs, Create PR, and Run Tests

on:
  schedule:
    - cron: "5 14 * * 0,4"
  workflow_dispatch:

jobs:
  update-plugins:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ github.token }}
          ref: ${{ github.head_ref }}
      - uses: cachix/install-nix-action@v20
        with:
          github_access_token: ${{ github.token }}
      - name: Update inputs
        run: |
          nix flake update
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_user_name: NixNeovim-CI
          commit_user_email: ""
          commit_author: ""
          commit_message: 'CI: update inputs '
          file_pattern: flake.lock
          # push_options: '--force'
          branch: update-inputs-bot
          create_branch: true

      - name: Create Pull Request
        uses: actions/github-script@v5
        with:
          github-token: ${{ github.token }}
          script: |
            const title = "[BOT] Update inputs";
            const body = "This pull request is automatically generated by a GitHub Actions workflow.";
            const head = "update-input-bot";  # Replace with the name of your branch
            const base = "main";  # Replace with the name of your main branch

            const { data: pullRequest } = await github.pulls.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title,
              body,
              head,
              base,
            });

            console.log(`Pull Request created: ${pullRequest.html_url}`);

      - name: Run checks
        run: nix flake check -L

      - name: Merge Pull Request
        if: success()
        uses: actions/github-script@v5
        with:
          github-token: ${{ github.token }}
          script: |
            await github.pulls.merge({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
            });


